// AUTO-GENERATED by scripts/sync-relations.mjs from
// .claude/skills/greek-market/relations.md — do not hand-edit.
// Re-run `node scripts/sync-relations.mjs` after changing that file.

export const RELATION_SECTIONS = [
  {
    "id": "energy",
    "label": "Energy",
    "entries": [
      {
        "heading": "ΔΕΗ / PPC",
        "why": "\"The ex-public company\" is not a historical footnote — it explains why decisions that read as regulatory are also political, and why a story about ΔΕΗ's balance sheet is also a story about household bills.",
        "edges": [
          {
            "subject": "ΔΕΗ",
            "relation": "is",
            "detail": null,
            "object": "former state utility"
          },
          {
            "subject": "ΔΕΗ",
            "relation": "supplies",
            "detail": null,
            "object": "Greek electricity retail market"
          }
        ]
      },
      {
        "heading": "ΔΕΗ controls ΔΕΔΔΗΕ — 51%, with Macquarie at 49%",
        "why": "The most load-bearing relation on the site so far, and the 49% is not a footnote — it changes the reading in both directions.",
        "edges": [
          {
            "subject": "ΔΕΗ",
            "relation": "owns",
            "detail": "51%",
            "object": "ΔΕΔΔΗΕ"
          },
          {
            "subject": "Macquarie Asset Management",
            "relation": "owns",
            "detail": "49%",
            "object": "ΔΕΔΔΗΕ"
          },
          {
            "subject": "Macquarie Asset Management",
            "relation": "board-seats",
            "detail": "4of11",
            "object": "ΔΕΔΔΗΕ"
          },
          {
            "subject": "ΔΕΔΔΗΕ",
            "relation": "operates",
            "detail": null,
            "object": "electricity distribution network"
          }
        ]
      },
      {
        "heading": "ΑΔΜΗΕ / IPTO",
        "why": "Transmission and distribution are routinely conflated in coverage and are different businesses with different owners. When ΑΔΜΗΕ and ΔΕΔΔΗΕ tender jointly — as on the Rouf super-high-voltage centre — that is two balance sheets, not one. And a Chinese state utility holding a quarter of the transmission operator makes grid decisions geopolitical in a way distribution decisions are not.",
        "edges": [
          {
            "subject": "State Grid Corporation of China",
            "relation": "owns",
            "detail": "24%",
            "object": "ΑΔΜΗΕ"
          },
          {
            "subject": "State Grid International Development",
            "relation": "owns",
            "detail": "20%",
            "object": "Ariadne Interconnection"
          },
          {
            "subject": "ΑΔΜΗΕ",
            "relation": "owns",
            "detail": null,
            "object": "Ariadne Interconnection"
          },
          {
            "subject": "ΑΔΜΗΕ",
            "relation": "owns",
            "detail": "100%",
            "object": "Grid Telecom"
          },
          {
            "subject": "ΑΔΜΗΕ",
            "relation": "operates",
            "detail": null,
            "object": "electricity transmission network"
          }
        ]
      },
      {
        "heading": "ΔΕΗ operates telecom infrastructure through FiberGrid",
        "why": "This breaks the site's own category structure, and in a useful way. GR Wire files Telco and Energy as separate beats; in Greece the same physical asset serves both. Consequences that follow directly:",
        "edges": [
          {
            "subject": "ΔΕΗ",
            "relation": "owns",
            "detail": null,
            "object": "ΔΕΗ FiberGrid"
          },
          {
            "subject": "ΔΕΗ FiberGrid",
            "relation": "deploys-on",
            "detail": null,
            "object": "ΔΕΔΔΗΕ distribution network"
          },
          {
            "subject": "ΔΕΗ FiberGrid",
            "relation": "competes-with",
            "detail": null,
            "object": "ΟΤΕ"
          },
          {
            "subject": "ΔΕΗ FiberGrid",
            "relation": "competes-with",
            "detail": null,
            "object": "Vodafone"
          },
          {
            "subject": "ΔΕΗ FiberGrid",
            "relation": "competes-with",
            "detail": null,
            "object": "Nova"
          }
        ]
      },
      {
        "heading": "ΔΕΗ FiberGrid + Fiber2All — a 50-50 wholesale JV, at term-sheet stage",
        "why": "This corrects an inference that was wrong and would have been published. ΔΕΗ FiberGrid is **not** simply competing with Vodafone — they are proposing to merge their fibre assets. Two consequences:",
        "edges": [
          {
            "subject": "ΔΕΗ FiberGrid",
            "relation": "proposed-jv",
            "detail": "50-50",
            "object": "Fiber2All"
          },
          {
            "subject": "Vodafone Ελλάδας",
            "relation": "owns",
            "detail": "100%",
            "object": "Fiber2All"
          },
          {
            "subject": "proposed JV",
            "relation": "sells",
            "detail": null,
            "object": "wholesale FTTH only"
          }
        ]
      },
      {
        "heading": "Wholesale access — only the incumbent is obliged",
        "why": "\"Forced to\" and \"chooses to\" are different claims, and only one of them is about the law. Never write that Greek fibre operators are *required* to sell wholesale — that is true of the incumbent and false of everyone else. Write that a network is open, or that it sells wholesale, and leave compulsion out of it unless ΟΤΕ is the subject.",
        "edges": [
          {
            "subject": "ΟΤΕ",
            "relation": "obliged-to-offer",
            "detail": null,
            "object": "wholesale access"
          },
          {
            "subject": "ΔΕΗ FiberGrid",
            "relation": "offers-commercially",
            "detail": null,
            "object": "wholesale access"
          }
        ]
      },
      {
        "heading": "ΔΕΔΔΗΕ pole access — a safety bottleneck, not a tariff",
        "why": "This is the answer to the question of whether the poles are shared infrastructure, and it is more interesting than a yes or a no. They are reachable, but through a gate whose keeper is a sister company of the largest tenant. Both ΔΕΔΔΗΕ and ΔΕΗ FiberGrid sit under ΔΕΗ. A rival fibreco pays ΔΕΗ's subsidiary for the engineering that lets it compete with ΔΕΗ's other subsidiary. Nothing improper follows from that automatically — the safety requirement is real and non-negotiable — but it is a structural asymmetry, and no telecom regulator sets the price of it.",
        "edges": [
          {
            "subject": "ΔΕΔΔΗΕ",
            "relation": "controls-access-to",
            "detail": null,
            "object": "distribution poles"
          },
          {
            "subject": "third-party fibre operators",
            "relation": "must-pay",
            "detail": null,
            "object": "ΔΕΔΔΗΕ for design and engineering"
          },
          {
            "subject": "ΔΕΗ FiberGrid",
            "relation": "sister-company-of",
            "detail": null,
            "object": "ΔΕΔΔΗΕ"
          }
        ]
      },
      {
        "heading": "ΕΕΤΤ, and the boundary that leaves the poles uncovered",
        "why": "Two different bottlenecks, neither with a telecom regulator over it. ΟΤΕ's physical infrastructure was looked at and left alone. ΔΕΔΔΗΕ's poles were never ΕΕΤΤ's to look at — ΔΕΔΔΗΕ is regulated by ΡΑΑΕΥ, the *energy* authority, which has no remit over telecom competition and no reason to price pole access with fibre rivalry in mind.",
        "edges": [
          {
            "subject": "ΕΕΤΤ",
            "relation": "regulates",
            "detail": null,
            "object": "telecom market"
          },
          {
            "subject": "ΡΑΑΕΥ",
            "relation": "regulates",
            "detail": null,
            "object": "ΔΕΔΔΗΕ"
          },
          {
            "subject": "ΕΕΤΤ",
            "relation": "attempted-and-abandoned",
            "detail": null,
            "object": "regulation of ΟΤΕ physical infrastructure access"
          }
        ]
      },
      {
        "heading": "ΡΑΑΕΥ / RAAEY",
        "why": "Independence is the point. When ΡΑΑΕΥ weighs a measure and a minister comments on it, those are two different actors and the distinction is worth preserving in the text — the minister is describing, not deciding.",
        "edges": [
          {
            "subject": "ΡΑΑΕΥ",
            "relation": "regulates",
            "detail": null,
            "object": "ΔΕΗ"
          },
          {
            "subject": "ΡΑΑΕΥ",
            "relation": "regulates",
            "detail": null,
            "object": "ΔΕΔΔΗΕ"
          },
          {
            "subject": "ΡΑΑΕΥ",
            "relation": "regulates",
            "detail": null,
            "object": "ΑΔΜΗΕ"
          },
          {
            "subject": "ΡΑΑΕΥ",
            "relation": "independent-of",
            "detail": null,
            "object": "Ministry of Energy"
          }
        ]
      }
    ]
  },
  {
    "id": "telecom",
    "label": "Telecom",
    "entries": [
      {
        "heading": "The fibercos",
        "why": "\"Fibre in Greece\" is not one market. There is a wholesale layer and a retail layer, and a backbone layer beneath both, and the same groups sit on more than one — which is why a fibre story needs the layer named before anything else in it can be read correctly.",
        "edges": [
          {
            "subject": "Vodafone Ελλάδας",
            "relation": "owns",
            "detail": null,
            "object": "Fiber2All"
          },
          {
            "subject": "Nova",
            "relation": "owns",
            "detail": null,
            "object": "UnitedFiber"
          },
          {
            "subject": "ΔΕΗ",
            "relation": "owns",
            "detail": null,
            "object": "ΔΕΗ FiberGrid"
          },
          {
            "subject": "ΑΔΜΗΕ",
            "relation": "owns",
            "detail": null,
            "object": "Grid Telecom"
          }
        ]
      },
      {
        "heading": "Grid Telecom — ΑΔΜΗΕ's fibre arm, on the transmission network",
        "why": "There are **two** grid-borne fibre businesses in Greece, on two different electricity networks, under two different owners — and conflating them would be an obvious error to anyone in the market.",
        "edges": [
          {
            "subject": "ΑΔΜΗΕ",
            "relation": "owns",
            "detail": "100%",
            "object": "Grid Telecom"
          },
          {
            "subject": "Grid Telecom",
            "relation": "deploys-on",
            "detail": null,
            "object": "electricity transmission network"
          },
          {
            "subject": "Grid Telecom",
            "relation": "sells",
            "detail": null,
            "object": "dark fibre wholesale"
          },
          {
            "subject": "Grid Telecom",
            "relation": "mou-with",
            "detail": null,
            "object": "ESO EAD"
          },
          {
            "subject": "Grid Telecom",
            "relation": "builds",
            "detail": null,
            "object": "Crete international data gateway"
          }
        ]
      },
      {
        "heading": "ΟΤΕ and UnitedFiber — RUMOUR, NOT FOR PUBLICATION",
        "why": "As a signal, it says the whole wholesale layer may be consolidating into two or three neutral platforms rather than four operator-owned ones, and that is worth watching for.",
        "edges": []
      }
    ]
  },
  {
    "id": "finance",
    "label": "Finance",
    "entries": []
  }
];

export const RELATION_EDGES = RELATION_SECTIONS.flatMap((s) =>
  s.entries.flatMap((e) =>
    e.edges.map((edge) => ({ ...edge, section: s.id, heading: e.heading, why: e.why }))
  )
);
